[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false

remappings = [
    '@account-abstraction/contracts/=lib/account-abstraction/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@lens-protocol/contracts/=lib/core/contracts/',
    '@erc6551/contracts/=lib/reference/src/',
    '@tokenbound/contracts/=lib/contracts/src/',
    'forge-std/=lib/forge-std/src/'
    ]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC}"

[etherscan]
mumbai = { key = "${MUMBAI_ETHERSCAN_API_KEY}", chain = 80001 }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config